// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: proto/robot.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Robot status enum
type RobotStatus int32

const (
	RobotStatus_UNKNOWN           RobotStatus = 0
	RobotStatus_IDLE              RobotStatus = 1
	RobotStatus_ASSIGNED          RobotStatus = 2
	RobotStatus_MOVING_TO_PICKUP  RobotStatus = 3
	RobotStatus_AT_PICKUP         RobotStatus = 4
	RobotStatus_MOVING_TO_DROPOFF RobotStatus = 5
	RobotStatus_AT_DROPOFF        RobotStatus = 6
	RobotStatus_RETURNING         RobotStatus = 7
	RobotStatus_CHARGING          RobotStatus = 8
	RobotStatus_OFFLINE           RobotStatus = 9
	RobotStatus_ERROR             RobotStatus = 10
	RobotStatus_MAINTENANCE       RobotStatus = 11
)

// Enum value maps for RobotStatus.
var (
	RobotStatus_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "IDLE",
		2:  "ASSIGNED",
		3:  "MOVING_TO_PICKUP",
		4:  "AT_PICKUP",
		5:  "MOVING_TO_DROPOFF",
		6:  "AT_DROPOFF",
		7:  "RETURNING",
		8:  "CHARGING",
		9:  "OFFLINE",
		10: "ERROR",
		11: "MAINTENANCE",
	}
	RobotStatus_value = map[string]int32{
		"UNKNOWN":           0,
		"IDLE":              1,
		"ASSIGNED":          2,
		"MOVING_TO_PICKUP":  3,
		"AT_PICKUP":         4,
		"MOVING_TO_DROPOFF": 5,
		"AT_DROPOFF":        6,
		"RETURNING":         7,
		"CHARGING":          8,
		"OFFLINE":           9,
		"ERROR":             10,
		"MAINTENANCE":       11,
	}
)

func (x RobotStatus) Enum() *RobotStatus {
	p := new(RobotStatus)
	*p = x
	return p
}

func (x RobotStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RobotStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_robot_proto_enumTypes[0].Descriptor()
}

func (RobotStatus) Type() protoreflect.EnumType {
	return &file_proto_robot_proto_enumTypes[0]
}

func (x RobotStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RobotStatus.Descriptor instead.
func (RobotStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

// Position update message
type PositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`    // Direction in degrees (0-360)
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`        // Speed in m/s
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

func (x *PositionUpdate) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *PositionUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PositionUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PositionUpdate) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *PositionUpdate) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PositionUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Battery update message
type BatteryUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	BatteryLevel  float32                `protobuf:"fixed32,2,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"` // Battery percentage (0-100)
	IsCharging    bool                   `protobuf:"varint,3,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryUpdate) Reset() {
	*x = BatteryUpdate{}
	mi := &file_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryUpdate) ProtoMessage() {}

func (x *BatteryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryUpdate.ProtoReflect.Descriptor instead.
func (*BatteryUpdate) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{1}
}

func (x *BatteryUpdate) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *BatteryUpdate) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *BatteryUpdate) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *BatteryUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Status update message
type StatusUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RobotId        string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Status         RobotStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=robot.RobotStatus" json:"status,omitempty"`
	CurrentOrderId string                 `protobuf:"bytes,3,opt,name=current_order_id,json=currentOrderId,proto3" json:"current_order_id,omitempty"` // Empty if no active order
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`         // Error details if status is ERROR
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusUpdate) Reset() {
	*x = StatusUpdate{}
	mi := &file_proto_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusUpdate) ProtoMessage() {}

func (x *StatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusUpdate.ProtoReflect.Descriptor instead.
func (*StatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{2}
}

func (x *StatusUpdate) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *StatusUpdate) GetStatus() RobotStatus {
	if x != nil {
		return x.Status
	}
	return RobotStatus_UNKNOWN
}

func (x *StatusUpdate) GetCurrentOrderId() string {
	if x != nil {
		return x.CurrentOrderId
	}
	return ""
}

func (x *StatusUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StatusUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Combined update message for streaming
type RobotUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RobotUpdate_Position
	//	*RobotUpdate_Battery
	//	*RobotUpdate_Status
	Update        isRobotUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotUpdate) Reset() {
	*x = RobotUpdate{}
	mi := &file_proto_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotUpdate) ProtoMessage() {}

func (x *RobotUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotUpdate.ProtoReflect.Descriptor instead.
func (*RobotUpdate) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{3}
}

func (x *RobotUpdate) GetUpdate() isRobotUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RobotUpdate) GetPosition() *PositionUpdate {
	if x != nil {
		if x, ok := x.Update.(*RobotUpdate_Position); ok {
			return x.Position
		}
	}
	return nil
}

func (x *RobotUpdate) GetBattery() *BatteryUpdate {
	if x != nil {
		if x, ok := x.Update.(*RobotUpdate_Battery); ok {
			return x.Battery
		}
	}
	return nil
}

func (x *RobotUpdate) GetStatus() *StatusUpdate {
	if x != nil {
		if x, ok := x.Update.(*RobotUpdate_Status); ok {
			return x.Status
		}
	}
	return nil
}

type isRobotUpdate_Update interface {
	isRobotUpdate_Update()
}

type RobotUpdate_Position struct {
	Position *PositionUpdate `protobuf:"bytes,1,opt,name=position,proto3,oneof"`
}

type RobotUpdate_Battery struct {
	Battery *BatteryUpdate `protobuf:"bytes,2,opt,name=battery,proto3,oneof"`
}

type RobotUpdate_Status struct {
	Status *StatusUpdate `protobuf:"bytes,3,opt,name=status,proto3,oneof"`
}

func (*RobotUpdate_Position) isRobotUpdate_Update() {}

func (*RobotUpdate_Battery) isRobotUpdate_Update() {}

func (*RobotUpdate_Status) isRobotUpdate_Update() {}

// Acknowledgment messages
type PositionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionAck) Reset() {
	*x = PositionAck{}
	mi := &file_proto_robot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionAck) ProtoMessage() {}

func (x *PositionAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionAck.ProtoReflect.Descriptor instead.
func (*PositionAck) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{4}
}

func (x *PositionAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PositionAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BatteryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatteryAck) Reset() {
	*x = BatteryAck{}
	mi := &file_proto_robot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatteryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatteryAck) ProtoMessage() {}

func (x *BatteryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatteryAck.ProtoReflect.Descriptor instead.
func (*BatteryAck) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{5}
}

func (x *BatteryAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatteryAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusAck) Reset() {
	*x = StatusAck{}
	mi := &file_proto_robot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAck) ProtoMessage() {}

func (x *StatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAck.ProtoReflect.Descriptor instead.
func (*StatusAck) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{6}
}

func (x *StatusAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAck) Reset() {
	*x = UpdateAck{}
	mi := &file_proto_robot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAck) ProtoMessage() {}

func (x *UpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAck.ProtoReflect.Descriptor instead.
func (*UpdateAck) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAck) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_robot_proto protoreflect.FileDescriptor

const file_proto_robot_proto_rawDesc = "" +
	"\n" +
	"\x11proto/robot.proto\x12\x05robot\"\xb3\x01\n" +
	"\x0ePositionUpdate\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x8e\x01\n" +
	"\rBatteryUpdate\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12#\n" +
	"\rbattery_level\x18\x02 \x01(\x02R\fbatteryLevel\x12\x1f\n" +
	"\vis_charging\x18\x03 \x01(\bR\n" +
	"isCharging\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc2\x01\n" +
	"\fStatusUpdate\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.robot.RobotStatusR\x06status\x12(\n" +
	"\x10current_order_id\x18\x03 \x01(\tR\x0ecurrentOrderId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xad\x01\n" +
	"\vRobotUpdate\x123\n" +
	"\bposition\x18\x01 \x01(\v2\x15.robot.PositionUpdateH\x00R\bposition\x120\n" +
	"\abattery\x18\x02 \x01(\v2\x14.robot.BatteryUpdateH\x00R\abattery\x12-\n" +
	"\x06status\x18\x03 \x01(\v2\x13.robot.StatusUpdateH\x00R\x06statusB\b\n" +
	"\x06update\"A\n" +
	"\vPositionAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\n" +
	"BatteryAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\tStatusAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\tUpdateAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp*\xc4\x01\n" +
	"\vRobotStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04IDLE\x10\x01\x12\f\n" +
	"\bASSIGNED\x10\x02\x12\x14\n" +
	"\x10MOVING_TO_PICKUP\x10\x03\x12\r\n" +
	"\tAT_PICKUP\x10\x04\x12\x15\n" +
	"\x11MOVING_TO_DROPOFF\x10\x05\x12\x0e\n" +
	"\n" +
	"AT_DROPOFF\x10\x06\x12\r\n" +
	"\tRETURNING\x10\a\x12\f\n" +
	"\bCHARGING\x10\b\x12\v\n" +
	"\aOFFLINE\x10\t\x12\t\n" +
	"\x05ERROR\x10\n" +
	"\x12\x0f\n" +
	"\vMAINTENANCE\x10\v2\xf7\x01\n" +
	"\fRobotService\x12;\n" +
	"\x0eUpdatePosition\x12\x15.robot.PositionUpdate\x1a\x12.robot.PositionAck\x128\n" +
	"\rUpdateBattery\x12\x14.robot.BatteryUpdate\x1a\x11.robot.BatteryAck\x125\n" +
	"\fUpdateStatus\x12\x13.robot.StatusUpdate\x1a\x10.robot.StatusAck\x129\n" +
	"\rStreamUpdates\x12\x12.robot.RobotUpdate\x1a\x10.robot.UpdateAck(\x010\x01B\x16Z\x14/proto;order_serviceb\x06proto3"

var (
	file_proto_robot_proto_rawDescOnce sync.Once
	file_proto_robot_proto_rawDescData []byte
)

func file_proto_robot_proto_rawDescGZIP() []byte {
	file_proto_robot_proto_rawDescOnce.Do(func() {
		file_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)))
	})
	return file_proto_robot_proto_rawDescData
}

var file_proto_robot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_robot_proto_goTypes = []any{
	(RobotStatus)(0),       // 0: robot.RobotStatus
	(*PositionUpdate)(nil), // 1: robot.PositionUpdate
	(*BatteryUpdate)(nil),  // 2: robot.BatteryUpdate
	(*StatusUpdate)(nil),   // 3: robot.StatusUpdate
	(*RobotUpdate)(nil),    // 4: robot.RobotUpdate
	(*PositionAck)(nil),    // 5: robot.PositionAck
	(*BatteryAck)(nil),     // 6: robot.BatteryAck
	(*StatusAck)(nil),      // 7: robot.StatusAck
	(*UpdateAck)(nil),      // 8: robot.UpdateAck
}
var file_proto_robot_proto_depIdxs = []int32{
	0, // 0: robot.StatusUpdate.status:type_name -> robot.RobotStatus
	1, // 1: robot.RobotUpdate.position:type_name -> robot.PositionUpdate
	2, // 2: robot.RobotUpdate.battery:type_name -> robot.BatteryUpdate
	3, // 3: robot.RobotUpdate.status:type_name -> robot.StatusUpdate
	1, // 4: robot.RobotService.UpdatePosition:input_type -> robot.PositionUpdate
	2, // 5: robot.RobotService.UpdateBattery:input_type -> robot.BatteryUpdate
	3, // 6: robot.RobotService.UpdateStatus:input_type -> robot.StatusUpdate
	4, // 7: robot.RobotService.StreamUpdates:input_type -> robot.RobotUpdate
	5, // 8: robot.RobotService.UpdatePosition:output_type -> robot.PositionAck
	6, // 9: robot.RobotService.UpdateBattery:output_type -> robot.BatteryAck
	7, // 10: robot.RobotService.UpdateStatus:output_type -> robot.StatusAck
	8, // 11: robot.RobotService.StreamUpdates:output_type -> robot.UpdateAck
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_robot_proto_init() }
func file_proto_robot_proto_init() {
	if File_proto_robot_proto != nil {
		return
	}
	file_proto_robot_proto_msgTypes[3].OneofWrappers = []any{
		(*RobotUpdate_Position)(nil),
		(*RobotUpdate_Battery)(nil),
		(*RobotUpdate_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_robot_proto_goTypes,
		DependencyIndexes: file_proto_robot_proto_depIdxs,
		EnumInfos:         file_proto_robot_proto_enumTypes,
		MessageInfos:      file_proto_robot_proto_msgTypes,
	}.Build()
	File_proto_robot_proto = out.File
	file_proto_robot_proto_goTypes = nil
	file_proto_robot_proto_depIdxs = nil
}
