// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: proto/robot.proto

package order_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotService_UpdatePosition_FullMethodName = "/robot.RobotService/UpdatePosition"
	RobotService_UpdateBattery_FullMethodName  = "/robot.RobotService/UpdateBattery"
	RobotService_UpdateStatus_FullMethodName   = "/robot.RobotService/UpdateStatus"
	RobotService_StreamUpdates_FullMethodName  = "/robot.RobotService/StreamUpdates"
)

// RobotServiceClient is the client API for RobotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Robot service for handling robot-to-server communication
type RobotServiceClient interface {
	// Send position updates from robot to server
	UpdatePosition(ctx context.Context, in *PositionUpdate, opts ...grpc.CallOption) (*PositionAck, error)
	// Send battery level updates
	UpdateBattery(ctx context.Context, in *BatteryUpdate, opts ...grpc.CallOption) (*BatteryAck, error)
	// Send status changes (idle, moving, delivering, etc.)
	UpdateStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*StatusAck, error)
	// Stream multiple updates (more efficient for frequent updates)
	StreamUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotUpdate, UpdateAck], error)
}

type robotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotServiceClient(cc grpc.ClientConnInterface) RobotServiceClient {
	return &robotServiceClient{cc}
}

func (c *robotServiceClient) UpdatePosition(ctx context.Context, in *PositionUpdate, opts ...grpc.CallOption) (*PositionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionAck)
	err := c.cc.Invoke(ctx, RobotService_UpdatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) UpdateBattery(ctx context.Context, in *BatteryUpdate, opts ...grpc.CallOption) (*BatteryAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatteryAck)
	err := c.cc.Invoke(ctx, RobotService_UpdateBattery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) UpdateStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*StatusAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusAck)
	err := c.cc.Invoke(ctx, RobotService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServiceClient) StreamUpdates(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RobotUpdate, UpdateAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotService_ServiceDesc.Streams[0], RobotService_StreamUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RobotUpdate, UpdateAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotService_StreamUpdatesClient = grpc.BidiStreamingClient[RobotUpdate, UpdateAck]

// RobotServiceServer is the server API for RobotService service.
// All implementations must embed UnimplementedRobotServiceServer
// for forward compatibility.
//
// Robot service for handling robot-to-server communication
type RobotServiceServer interface {
	// Send position updates from robot to server
	UpdatePosition(context.Context, *PositionUpdate) (*PositionAck, error)
	// Send battery level updates
	UpdateBattery(context.Context, *BatteryUpdate) (*BatteryAck, error)
	// Send status changes (idle, moving, delivering, etc.)
	UpdateStatus(context.Context, *StatusUpdate) (*StatusAck, error)
	// Stream multiple updates (more efficient for frequent updates)
	StreamUpdates(grpc.BidiStreamingServer[RobotUpdate, UpdateAck]) error
	mustEmbedUnimplementedRobotServiceServer()
}

// UnimplementedRobotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotServiceServer struct{}

func (UnimplementedRobotServiceServer) UpdatePosition(context.Context, *PositionUpdate) (*PositionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedRobotServiceServer) UpdateBattery(context.Context, *BatteryUpdate) (*BatteryAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBattery not implemented")
}
func (UnimplementedRobotServiceServer) UpdateStatus(context.Context, *StatusUpdate) (*StatusAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedRobotServiceServer) StreamUpdates(grpc.BidiStreamingServer[RobotUpdate, UpdateAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamUpdates not implemented")
}
func (UnimplementedRobotServiceServer) mustEmbedUnimplementedRobotServiceServer() {}
func (UnimplementedRobotServiceServer) testEmbeddedByValue()                      {}

// UnsafeRobotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotServiceServer will
// result in compilation errors.
type UnsafeRobotServiceServer interface {
	mustEmbedUnimplementedRobotServiceServer()
}

func RegisterRobotServiceServer(s grpc.ServiceRegistrar, srv RobotServiceServer) {
	// If the following call pancis, it indicates UnimplementedRobotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotService_ServiceDesc, srv)
}

func _RobotService_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_UpdatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).UpdatePosition(ctx, req.(*PositionUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_UpdateBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatteryUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).UpdateBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_UpdateBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).UpdateBattery(ctx, req.(*BatteryUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServiceServer).UpdateStatus(ctx, req.(*StatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotService_StreamUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RobotServiceServer).StreamUpdates(&grpc.GenericServerStream[RobotUpdate, UpdateAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotService_StreamUpdatesServer = grpc.BidiStreamingServer[RobotUpdate, UpdateAck]

// RobotService_ServiceDesc is the grpc.ServiceDesc for RobotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robot.RobotService",
	HandlerType: (*RobotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePosition",
			Handler:    _RobotService_UpdatePosition_Handler,
		},
		{
			MethodName: "UpdateBattery",
			Handler:    _RobotService_UpdateBattery_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _RobotService_UpdateStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUpdates",
			Handler:       _RobotService_StreamUpdates_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/robot.proto",
}
